const lines = [
  "<name> makes the ship run",
  "<name> steers the ship",
  "<name> keeps this thing in the sky",
  "<name> keeps this place running",
  "<name> is a force to be reckoned with",
  "<name> is the lone voice of reason in an otherwise insane world",
  "<name> is a blizzard that actually shows up",
  "<name> is like a memory of summer in a winter that seems to go on forever",
  "<name> is the smell of clean laundry",
  "<name> is a Netflix login that your friends being cool and letting you use for a while",
  "<name> is a comforter accidentally warmed by the radiator",
  "<name> is the smell of my grandma's kitchen",
  "<name> is the band you discovered in highschool long before anyone else did",
  "<name> is a catharsis that you only reach after years of therapy and after you've almost given up on yourself",
  "<name>... Is a pregnant pause before good news",
  "<name> is a three day weekend",
  "<name> is a buzzer beater at half court",
  "<name> is a nap in a hammock",
  "<name> is a gift you weren't expecting",
  "<name> is a window in a room where you didn't think there was one",
  "<name> is something you think is impossible, but you have to try anyway",
  "<name> is the confidence to fight the self-doubt that keeps you from being yourself",
  "<name> is the T-shirt you don’t wash because you’re afraid it will shrink",
  "<name> is the free garlic knots with your pizza",
  "<name> is your friend’s swimming pool, he said its okay if you come by",
  "<name> is that rock quarry you’ve been swimming at for years, and still no one else seems to know about it",
  "<name> is that moment when you realize that person you’ve been crushing on all semester, might just like you back",
  "<name> is a new haircut that’s not all messed up and weird",
  "<name> is an old movie that still holds up",
  "<name> is the solution to a problem that’s been bothering you for a while",
  "<name> is Estonia",
  "<name> is that moment when the band you love comes out for an encore.",
  "<name> is reading the credits",
  "<name> is a jump off a high dive",
  "<name> is a night to yourself just long enough so you remember you like other people",
  "<name> is a book you stay up and read in one night",
  "<name> is that cousin you only see during the summer but you get along as though you hang out all the time",
  "<name> is good advice from an old friend",
  "<name> is waking up in a tent so far from civilization that you cant even hear the distant hush of tires",
  "<name> is a surprise party that you secretly hoped for, but you never let yourself expect",
  "<name> is a piper at the gates of dawn",
  "<name> is a rope swing over a pond",
  "<name> is a conversation so engrossing that the only thing that snaps you out of it, is the sun coming up",
  "<name> is a spontaneous road trip",
  "<name> is finally finding the name of that movie that you saw as a kid that was so weird and vivid that you didn't know if you dreamt it or not",
  "<name> is when you run into a friend on the street and you end up just spending the day walking around",
  "<name> is the quiet stillness of the year's first snowfall",
  "<name> is the phone that you dropped out of your hand onto the sidewalk, pick up in sheer horror, look at and realize that it is somehow completely unharmed",
  "<name> is one of those nights that is so fun and gets so out of hand that when you describe it to your friends you can tell that they don't totally believe you",
  "<name> is the person who can fix the things that are broken and complicated",
  "<name> is a word you finally remember",
  "<name> is the first day of the year where everyone walks around carrying the coats that they just realized they don't need to wear",
  "<name> is a killer drum break",
  "<name> is one more hour of sleep",
  "<name> is light itself - coursing throughout the city spreading information",
  "<name> is an animated gif of a mailman furiously beating a mailbox with a baseball bat",
  "<name> is the chairman of Wayne enterprises",
  "<name> is a weekend with good weather and no plans",
  "<name> is the salsa dancer emoji",
  "<name> is a mouse pad with a kitten in a basket on it",
  "<name> is the first day of the year that you can fall asleep with the window open",
  "<name> is a new puppy that finally sleeps through the night",
  "<name> is a nap in a park",
  "<name> is the smoke from fireworks",
  "<name> is a summer night where you somehow get the ratio of thin sheet to heavy sheet and air conditioner to window to finally line up and you are not hot and you are not too cold and you actually sleep",
  "<name> is tubing down a lazy river, towing a 6 pack",
  "<name> is a plate of very fancy cold cuts",
  "<name> is a long lunch",
  "<name> is cicada season",
  "<name> is a three day weekend you COMPLETELY forgot about",
  "<name> is the sound of your favorite person laughing",
  "<name> is a dingy hotel in a small town that somehow has your favorite pinball game",
  "<name> is the directors cut of Aliens. NOT the theatrical release",
  "<name> is a perfect Halloween costume",
  "<name> is money you find in a winter coat",
  "<name> is a new season of a long cancelled television show that's actually as good as it was when it was originally on the air",
  "<name> is a late night phone call from a friend",
  "<name> is a space heater on cold feat",
  "<name> is launching your sled off a killer jump",
  "<name> is your first big laugh at the office after a long vacation",
  "<name> is a cure for what ails you",
  "<name> is a world that doesn't make sense in a way that's safe and joyful and feels really good",
  "<name> is driving with the windows down singing your favorite song as loud as you can",
  "<name> is hoodie weather",
  "<name> is a miraculous parking spot",
  "<name> is four extra beers in the fridge that you forgot were even there",
  "<name> is a new kind of sandwich you've never seen before",
  "<name> is a lost t-shirt that just shows up one day",
  "<name> is the first cookout of the year",
  "<name> is the satisfaction of pressing send on an email that you've agonized over for a year",
  "<name> is a balmy summer night just hanging out on the back porch, doing whatever",
  "<name> is bubble tea",
  "<name> is a playlist that has that Beach Boys song 'Wind Chimes' on it, but then right after that song ends, 'Snowblind' by Black Sabbath comes on",
  "<name> is a potluck dinner on a picnic table in the shade on a balmy evening",
  "<name> is an all mango fruit basket",
  "<name> is a book you read in one sitting",
  "<name> is the best part of the summer",
  "<name> is a bonfire on a beach",
  "<name> is a job that you love so much that you actually sort of forget to go outside. and then one day you just find yourself wondering 'Has the 4th of July happened yet?' and so you look out a window and you realize actually its the end of august, summers almost over and you just feel this tiny little teaspoon of regret. And then you realize, you could just go outside. The building has an elevator. What if you took it?",
  "<name> is those Popsicle's you thought you were never going to find at the deli again",
  "<name> is one last softball game at the end of summer",
  "<name> is getting back on your bike after you haven't ridden it in a really long time",
  "<name> is when you're sitting on the couch flipping thru channels and you find a movie you haven't seen in a long time and you just sit there and watch the whole thing",
  "<name> is a dog who sleeps on your keyboard",
  "<name> is sitting on your couch and looking around at how nice your house looks after you just cleaned it",
  "<name> is cookies somebody brought to the office",
  "<name> is a room that is at the perfect temperature",
  "<name> is snow before you get sick of it",
  "<name> is the day where everybody brings their extra baked goods to the office",
  "<name> is an unseasonably warm day",
  "<name> is a vending machine that gives you two of the thing you wanted by mistake",
  "<name> is candy you've never heard of from some other country",
  "<name> is listening to the radio and hearing that song you've heard sampled a million times, but you never knew the name of",
  "<name> is that week where it finally gets warm enought that the last of the snow melts",
  "<name> is the closest parking spot to the movie theater",
  "<name> is food that is the appropriate amount of spicy",
  "<name> is just getting to do credits in a normal way without some weird interloper coming in the room",
  "<name> is the incredible satisfation of making that someone special laugh",
  "<name> is your favorite group chat",
  "<name> is going to see a summer blockbuster on a 100 degree day in a theater that has its air conditioning cranked way up",
  "<name> is driving with the windows down and the music up",
  "<name> is a thermostat at a temperature that everyone in the room can agree on",
  "<name> is 10 hours of sleep",
  "<name> is a walk in the woods",
  "<name> is a long drive at night",
  "<name> is a video that you find so funny that you force your coworkers to watch over and over and over again until they start enjoying it",
  "<name> is getting a phone call and having it not turn out to be spam",
  "<name> is a good excuse to get dressed up",
  "<name> is when you're folding your laundry and find 5 bucks in one of your pants pockets",
  "<name> is one of those cotton candy machines where you get to dump in the like, cotton candy mixture and then you turn it on and you put a stick in there and cotton candy magically weaves out of thin air onto the stick",
  "<name> is one of those free samples of fudge you get on the boardwalk by the beach",
  "<name> is Sunday at the farmer's market",
  "<name> is a random interaction with a stranger where afterward, you don't feel awkward",
];

export default (name) => {
  const length = lines.length;
  let line = lines[Math.floor(Math.random() * length)];
  line = line.replace("<name>", name);
  return line;
};
